# Generated by Django 4.2 on 2024-02-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=255, verbose_name='LastName')),
                ('phone_number', models.CharField(max_length=255, verbose_name='PhoneNumber')),
                ('address', models.TextField(verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('id',),
            },
        ),
    ]
